services:
  db:
    build: db
    #image: mariadb:10.11.3-jammy
    command: '--default-authentication-plugin=mysql_native_password'

    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/tmp/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
  backend:
    build: app
    restart: always
    secrets:
      - db-password
    ports: 
      - 8000:8000
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    networks:
      - backnet
      - frontnet
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
  frontnet:
